#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Hubs,  S2, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S3,     BumpBottomLift, sensorTouch)
#pragma config(Motor,  motorA,          Intake_Left,   tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          Intake_Right,  tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_1, LiftRight,     tmotorMatrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_Matrix_S1_2, Right_Back,    tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S1_3, Right_Front,   tmotorMatrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_Matrix_S1_4, Conveyor,      tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S2_1, LiftLeft,      tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S2_2, Spindle,       tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S2_3, Left_Back,     tmotorMatrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_Matrix_S2_4, Left_Front,    tmotorMatrix, openLoop, encoder)
#pragma config(Servo,  srvo_Matrix_S1_1, BoxDoor,              tServoStandard)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, BoxArm,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_1, servo5,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_2, SecondaryHolder,      tServoStandard)
#pragma config(Servo,  srvo_Matrix_S2_3, servo7,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_4, Holder,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "Drive.c"
#include "Lift.c"
#include "Intake.c"

/* TODO:
 * Test all Teleoperated functions
 * Test lift presets
 */

// Initialization on your robot and the variables within your program.
void initializeRobot()
{
	raiseHook();
	raiseSecondaryHook();

	closeBoxDoor();
	moveBoxArmToStart();

	zeroDriveEncoders();

	return;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
// The following is the main code for the tele-op robot operation.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot();

	int x = 0;
	int y = 0;
	int controls = 1;
	int held = 1;

	waitForStart();

	while (true)
	{
		getJoystickSettings(joystick);

		if(controls == 1)
		{
			x = joystick.joy1_y1;
			y = joystick.joy1_y2;
		}
		else
		{
			x = -joystick.joy1_y2;
			y = -joystick.joy1_y1;
		}

		x = abs(x) > driveJoystickDeadzone ? x : 0;
		y = abs(y) > driveJoystickDeadzone ? y : 0;

		tankDrive(x, y);

		//control scheme switching
		if(held == 1)
		{
			if(joy1Btn(3) == 0)
			{
				held = 0;
			}
		}
		else
		{
			if(joy1Btn(9) == 1)
			{
				if(controls == 1)
				{
					controls = 2;
				}
				else
				{
					controls = 1;
				}

				held = 1;
			}
		}

		if(joy2Btn(1) == 1)
		{
			currentLiftTarget = liftTargets[0];
		}
		else if(joy2Btn(2) == 1)
		{
			currentLiftTarget = liftTargets[1];
		}
		else if(joy2Btn(3) == 1)
		{
			currentLiftTarget = liftTargets[2];
		}
		else if(joy2Btn(4) == 1)
		{
			currentLiftTarget = liftTargets[3];
		}

		//updateLift();

		liftAtTarget = true;

		// Moves lift - controlled by right joystick on controller 2
		if(abs(joystick.joy2_y2) > liftJoystickDeadzone)
		{
			liftAtSpeed(joystick.joy2_y2);

			currentLiftTarget = nMotorEncoder[LiftRight];
		}
		else if(liftAtTarget)
		{
			if(currentLiftTarget > 1000)
			{
				liftAtSpeed(10);
			}
			else
			{
				liftAtSpeed(0);
			}
		}

		if(SensorValue[BumpBottomLift] == 1)
		{
			zeroLiftEncoders();

			if(currentLiftTarget < 0)
			{
				currentLiftTarget = 0;
			}
		}

		//Conveyor controlled by right 2 shoulder buttons (RT and RB)
		if(joy2Btn(6) == 1)
		{
			conveyorAtSpeed(conveyorSpeed);
		}
		else if(joy2Btn(8) == 1)
		{
			conveyorAtSpeed(-conveyorSpeed);
		}
		else
		{
			conveyorAtSpeed(0);
		}

		//Spindle: left shoulder buttons on both controllers (primarily the secondary controller
		//but both can do it with the same buttons controls secondary NXT intake also
		if(joy2Btn(5) == 1 || joy1Btn(5) == 1)
		{
			intakeAtSpeed(-intakeSpeed);
		}
		else if(joy2Btn(7) == 1 || joy1Btn(7) == 1)
		{
			intakeAtSpeed(intakeSpeed);
		}
		else
		{
			intakeAtSpeed(0);
		}

		if(joy1Btn(8) == 1 && joy1Btn(6) == 0)
		{
			lowerHook();
		}
		else if(joy1Btn(8) == 1 && joy1Btn(6) == 1)
		{
			halfHook();
		}
		else if(joy1Btn(8) == 0 && joy1Btn(6) == 1)
		{
			raiseHook();
		}

		if(joy1Btn(2) == 1 && joy1Btn(4) == 0)
		{
			lowerSecondaryHook();
		}
		else if(joy1Btn(2) == 0 && joy1Btn(4) == 1)
		{
			raiseSecondaryHook();
		}

		//BoxFlipper: left and right on the D-Pad make this move
		if(joystick.joy2_TopHat == 6)
		{
			servo[BoxArm] = boxArmEnd;
		}
		else if(joystick.joy2_TopHat == 2)
		{
			servo[BoxArm] = boxArmStart;
		}

		//BoxDoor: up and down on D-pad
		if(joystick.joy2_TopHat == 0) // D-Pad Up
		{
			servo[BoxDoor] = boxDoorOpen;
		}
		else if(joystick.joy2_TopHat == 4) //D-Pad Down
		{
			servo[BoxDoor] = boxDoorClosed;
		}

		nxtDisplayCenteredTextLine(2, "%d", nMotorEncoder[LiftLeft]);
		nxtDisplayCenteredTextLine(3, "%d", SensorValue[BumpBottomLift]);
	}
}
